// Editorial summaries of the linked NASA pages, not official translations.
// Do not mix these background descriptions with the fixed ephemeris date.
import { moonProfileRows } from './moon-profiles.js';
const rows = {
 ...moonProfileRows,
 '10':['sun/facts/','A star made mainly of hydrogen and helium, held together by gravity. Its layered interior and atmosphere extend from the core to the corona. Magnetic activity changes its appearance; the map here captures only a historical observation.','太阳主要由氢和氦组成，依靠自身引力聚集。内部和大气从核心延伸至日冕，具有分层结构。磁场活动会改变外观，本页地图只反映历史观测。','太陽主要由氫和氦組成，依靠自身引力聚集。內部和大氣從核心延伸至日冕，具有分層結構。磁場活動會改變外觀，本頁地圖只反映歷史觀測。','主に水素とヘリウムからなる恒星で、自身の重力でまとまっています。内部と大気は中心核からコロナまで層を成します。磁気活動で外観が変化し、ここでは過去の観測を表示しています。','주로 수소와 헬륨으로 이루어져 자체 중력으로 유지되는 항성입니다. 핵에서 코로나까지 층상 구조를 이루며 자기 활동에 따라 모습이 변합니다. 이 지도는 과거 관측을 보여줍니다.'],
 '199':['mercury/facts/','The smallest planet and closest to the Sun. A large metallic core lies beneath its rocky exterior. Impacts have heavily cratered the surface. Mercury has no moons or rings; its reference ellipsoid does not reproduce those craters as relief.','水星是最小、最靠近太阳的行星，岩石外壳之下有较大的金属核心。撞击在表面留下大量陨石坑。水星没有卫星和行星环；本模型的参考椭球不重建陨石坑高程。','水星是最小、最靠近太陽的行星，岩石外殼之下有較大的金屬核心。撞擊在表面留下大量隕石坑。水星沒有衛星和行星環；本模型的參考橢球不重建隕石坑高程。','最小で太陽に最も近い惑星です。岩石の外層の下に大きな金属核があり、表面には多数の衝突クレーターがあります。衛星や環はありません。モデルの基準楕円体はクレーターの起伏を再現しません。','가장 작고 태양에 가장 가까운 행성입니다. 암석 외층 아래 큰 금속 핵이 있고 표면에는 충돌 분화구가 많습니다. 위성과 고리는 없습니다. 기준 타원체 모델에는 분화구 높낮이가 없습니다.'],
 '299':['venus/venus-facts/','Venus is a rocky planet with a dense atmosphere and a surface hidden beneath clouds. Atmospheric greenhouse heating makes it exceptionally hot. Radar can reveal the terrain below the clouds; that is the kind of map displayed here.','金星是岩石行星，拥有浓密大气，地表隐藏在云层下。强烈温室效应使表面异常炎热。雷达能够揭示云下地形，本页展示的正是这类地表地图。','金星是岩石行星，擁有濃密大氣，地表隱藏在雲層下。強烈溫室效應使表面異常炎熱。雷達能夠揭示雲下地形，本頁展示的正是這類地表地圖。','厚い大気を持つ岩石惑星で、地表は雲に隠れています。強い温室効果で非常に高温です。レーダーで雲の下の地形を調べることができ、ここではその地表マップを表示します。','짙은 대기를 가진 암석 행성이며 지표는 구름 아래 숨겨져 있습니다. 강한 온실 효과로 매우 뜨겁습니다. 레이더로 구름 아래 지형을 볼 수 있으며 여기서는 그 지표 지도를 표시합니다.'],
 '399':['earth/facts/','Earth is a rocky world with liquid-water oceans and an atmosphere dominated by nitrogen and oxygen. The atmosphere shapes climate and weather and shields the surface from radiation and many incoming meteoroids. This cloud-free composite does not show current weather.','地球是拥有液态水海洋的岩石世界，大气以氮和氧为主。大气影响气候与天气，并屏蔽部分辐射、阻挡许多流星体。本页无云合成图不表示当前天气。','地球是擁有液態水海洋的岩石世界，大氣以氮和氧為主。大氣影響氣候與天氣，並屏蔽部分輻射、阻擋許多流星體。本頁無雲合成圖不表示目前天氣。','液体の海を持つ岩石の世界で、大気の主成分は窒素と酸素です。大気は気候や天候を左右し、放射線や多くの流星体から地表を守ります。この雲なし合成図は現在の天候ではありません。','액체 바다와 질소·산소 중심 대기를 가진 암석 세계입니다. 대기는 기후와 날씨를 형성하고 일부 방사선과 많은 유성체로부터 지표를 보호합니다. 이 구름 없는 합성도는 현재 날씨가 아닙니다.'],
 '499':['mars/facts/','Iron oxidation in rocks and dust gives Mars its reddish appearance. Ancient valleys, deltas and lakebeds record a wetter past. Its terrain includes giant volcanoes. Historical images can show surface patterns, but a reference ellipsoid cannot reproduce the topography.','岩石和尘埃中的铁氧化物使火星呈红色。古河谷、三角洲和湖床记录了更湿润的过去，地表还有巨型火山。历史影像显示地表纹理，参考椭球则不重建真实地形。','岩石和塵埃中的鐵氧化物使火星呈紅色。古河谷、三角洲和湖床記錄了更濕潤的過去，地表還有巨型火山。歷史影像顯示地表紋理，參考橢球則不重建真實地形。','岩石や塵の鉄の酸化で赤く見えます。古い河谷・デルタ・湖底は水の豊かだった過去を示し、巨大火山もあります。過去の画像は表面模様を示しますが、基準楕円体に実際の地形はありません。','암석과 먼지의 철 산화물이 붉은색을 만듭니다. 옛 계곡·삼각주·호수 바닥은 더 습했던 과거를 보여주며 거대한 화산도 있습니다. 과거 영상은 표면 무늬를 보여주지만 기준 타원체는 실제 지형을 재현하지 않습니다.'],
 '599':['jupiter/jupiter-facts/','Jupiter is the largest planet, a gas giant dominated by hydrogen and helium. Its visible bands are cloud systems rather than a solid surface. The changing atmosphere includes powerful storms. The historical OPAL map should not be read as present-day weather.','木星是最大的行星，是以氢和氦为主的气态巨行星。可见条带属于云系而非固体表面，大气不断变化并有强烈风暴。历史 OPAL 地图不能视作当前天气。','木星是最大的行星，是以氫和氦為主的氣態巨行星。可見條帶屬於雲系而非固體表面，大氣不斷變化並有強烈風暴。歷史 OPAL 地圖不能視作目前天氣。','最大の惑星で、水素とヘリウムを主成分とする巨大ガス惑星です。帯は固体表面ではなく雲で、変化する大気に強い嵐があります。過去の OPAL マップは現在の天候ではありません。','가장 큰 행성이며 수소와 헬륨 중심의 가스 거성입니다. 보이는 띠는 고체 표면이 아닌 구름이며 변화하는 대기에는 강력한 폭풍이 있습니다. 과거 OPAL 지도는 현재 날씨가 아닙니다.'],
 '699':['saturn/facts/','The sixth planet from the Sun and second largest, Saturn is mostly hydrogen and helium. Its interior is compressed into dense layers. A broad ring system surrounds the planet. Ring geometry and the illustrative appearance layer are documented separately in this atlas.','土星距太阳第六远、大小居第二，以氢和氦为主，内部在高压下形成致密层。宽阔环系统围绕行星。本图谱分别说明行星环的几何依据和示意外观。','土星距太陽第六遠、大小居第二，以氫和氦為主，內部在高壓下形成緻密層。寬闊環系統圍繞行星。本圖譜分別說明行星環的幾何依據和示意外觀。','太陽から 6 番目、2 番目に大きい惑星で、水素とヘリウムが主成分です。内部は高圧で高密度の層となり、広い環が取り巻きます。この図譜では環の寸法資料と模式的な外観を区別します。','태양에서 여섯 번째이자 두 번째로 큰 행성으로 수소와 헬륨이 주성분입니다. 내부는 고압으로 밀도 높은 층을 이루며 넓은 고리가 둘러쌉니다. 고리의 치수 근거와 예시 외관은 구분해 설명합니다.'],
 '799':['uranus/facts/','Uranus is an ice giant with an unusually tilted rotation axis, appearing to roll along its orbit. Models describe a hot, dense fluid interior containing water, methane and ammonia above a rocky core. The complete texture here is an illustration, not a full observational map.','天王星是冰巨星，自转轴倾斜很大，看起来像沿轨道滚动。内部模型包含岩核之上的高温高密度水、甲烷和氨流体。本页完整纹理是效果图，不是完整观测地图。','天王星是冰巨星，自轉軸傾斜很大，看起來像沿軌道滾動。內部模型包含岩核之上的高溫高密度水、甲烷和氨流體。本頁完整紋理是效果圖，不是完整觀測地圖。','自転軸が大きく傾き、軌道上を転がるように見える巨大氷惑星です。内部は岩石核の上に水・メタン・アンモニアを含む高温高密度流体があると考えられます。この全面テクスチャはイラストです。','자전축이 크게 기울어 궤도 위를 구르는 듯한 얼음 거성입니다. 내부 모델은 암석 핵 위에 물·메탄·암모니아를 포함한 뜨겁고 밀도 높은 유체를 설명합니다. 전체 텍스처는 완전 관측 지도가 아닌 그림입니다.'],
 '899':['neptune/neptune-facts/','Neptune is the eighth and most distant planet. It is an ice giant with a deep atmosphere rather than an accessible solid surface. Strong winds and evolving clouds shape its appearance. The illustration displayed here does not encode a particular day’s weather.','海王星是第八颗、距太阳最远的行星，是具有深厚大气的冰巨星，没有可直接踏上的固体表面。强风和变化的云层影响外观，本页效果图不表示某一天的天气。','海王星是第八顆、距太陽最遠的行星，是具有深厚大氣的冰巨星，沒有可直接踏上的固體表面。強風和變化的雲層影響外觀，本頁效果圖不表示某一天的天氣。','8 番目で最も遠い惑星です。厚い大気を持つ巨大氷惑星で、直接立てる固体表面はありません。強風と変化する雲が外観を作ります。表示中の図は特定日の天候ではありません。','여덟 번째이자 가장 먼 행성입니다. 깊은 대기를 가진 얼음 거성이며 직접 서 있을 고체 표면은 없습니다. 강풍과 변화하는 구름이 모습을 형성합니다. 표시된 그림은 특정일 날씨가 아닙니다.'],
 '999':['dwarf-planets/pluto/facts/','A Kuiper Belt dwarf planet with mountains, plains, glaciers and a thin atmosphere. Water ice forms rugged terrain, while nitrogen ice shapes prominent plains. Its large moon Charon is mutually tidally locked with Pluto.','冥王星是柯伊伯带矮行星，有山地、平原、冰川和稀薄大气。水冰形成崎岖地形，氮冰构成显著平原。大卫星卡戎与冥王星相互潮汐锁定。','冥王星是柯伊伯帶矮行星，有山地、平原、冰川和稀薄大氣。水冰形成崎嶇地形，氮冰構成顯著平原。大衛星卡戎與冥王星相互潮汐鎖定。','カイパーベルトの準惑星で、山・平原・氷河と薄い大気があります。水の氷が山地、窒素の氷が大きな平原を作ります。カロンとは互いに潮汐固定されています。','산·평원·빙하와 옅은 대기를 가진 카이퍼대 왜행성입니다. 물 얼음이 험한 지형을, 질소 얼음이 큰 평원을 만듭니다. 카론과 서로 조석 고정되어 있습니다.'],
 '301':['moon/facts/','Earth’s natural satellite has a heavily cratered surface and a very tenuous atmosphere. Some polar regions remain permanently shadowed and contain water ice. Observations and returned samples underpin its study; the visible map is processed imagery rather than a terrain mesh.','月球是地球的天然卫星，表面布满撞击坑，大气极其稀薄。部分极区永久阴影中有水冰。研究依赖观测与返回样品；本页展示处理后的影像，不是地形网格。','月球是地球的天然衛星，表面布滿撞擊坑，大氣極其稀薄。部分極區永久陰影中有水冰。研究依賴觀測與返回樣品；本頁展示處理後的影像，不是地形網格。','地球の自然衛星で、多くのクレーターと極めて薄い大気があります。極域の一部の永久影には水の氷があります。観測と持ち帰った試料が研究を支えます。表示は処理画像で地形メッシュではありません。','지구의 자연 위성으로 충돌 분화구가 많고 대기는 극히 희박합니다. 일부 극지 영구 그림자에는 물 얼음이 있습니다. 관측과 회수 시료로 연구되며 표시는 처리 영상이지 지형 메시가 아닙니다.'],
 '401':['mars/moons/phobos/','Phobos is the larger Martian moon. Its prominent Stickney crater records a major impact, and fine dust and displaced boulders are visible in spacecraft images. Its irregular shape is only approximated by the reference ellipsoid here.','火卫一是较大的火星卫星。显著的斯蒂克尼坑记录了大型撞击，探测器影像可见细尘和移动的巨石。本页参考椭球只能近似它的不规则形状。','火衛一是較大的火星衛星。顯著的斯蒂克尼坑記錄了大型撞擊，探測器影像可見細塵和移動的巨石。本頁參考橢球只能近似它的不規則形狀。','火星の大きい方の衛星です。大きな衝突を記録するスティックニー・クレーターが目立ち、画像には細かい塵や移動した岩が見られます。ここでは不規則な形を楕円体で近似します。','화성의 더 큰 위성입니다. 스티크니 분화구는 큰 충돌의 흔적이며 탐사선 영상에서 미세 먼지와 이동한 바위가 보입니다. 여기서는 불규칙 형상을 타원체로 근사합니다.'],
 '402':['mars/moons/deimos/','The smaller Martian moon is irregular and cratered. Its craters tend to be smaller than those on Phobos, and it lacks Phobos’s prominent grooves. Low gravity allows impact debris to escape its surface.','火卫二是较小的火星卫星，形状不规则、表面有撞击坑。坑通常比火卫一的小，缺少后者显著的沟槽。较弱引力使撞击碎屑容易离开表面。','火衛二是較小的火星衛星，形狀不規則、表面有撞擊坑。坑通常比火衛一的小，缺少後者顯著的溝槽。較弱引力使撞擊碎屑容易離開表面。','火星の小さい方の衛星で、不規則な形にクレーターがあります。フォボスより小さなクレーターが多く、目立つ溝はありません。重力が弱く衝突の破片は表面を離れやすくなります。','화성의 더 작은 위성으로 불규칙하고 분화구가 많습니다. 분화구는 대체로 포보스보다 작으며 포보스의 뚜렷한 홈은 없습니다. 약한 중력으로 충돌 파편이 표면을 벗어날 수 있습니다.'],
 '501':['jupiter/jupiter-moons/io/','Io’s abundant volcanic activity rapidly renews its surface. Fresh deposits cover old terrain faster than large impact craters can accumulate. This makes the historical colour mosaic a record of a changing volcanic world, not a permanently fixed surface.','木卫一火山活动丰富，能快速更新地表。新沉积覆盖旧地形的速度很快，大型撞击坑难以积累。因此历史彩图记录的是不断变化的火山世界。','木衛一火山活動豐富，能快速更新地表。新沉積覆蓋舊地形的速度很快，大型撞擊坑難以累積。因此歷史彩圖記錄的是不斷變化的火山世界。','豊富な火山活動が表面を急速に更新します。新しい堆積物が地形を覆うため、大型衝突クレーターが蓄積しにくい天体です。過去のカラー合成図は変化する火山世界の記録です。','활발한 화산 활동이 표면을 빠르게 갱신합니다. 새로운 퇴적물이 오래된 지형을 덮어 큰 충돌 분화구가 쌓이기 어렵습니다. 과거 색상 모자이크는 변화하는 화산 세계의 기록입니다.'],
 '502':['jupiter/jupiter-moons/europa/','Evidence strongly supports a salty ocean beneath Europa’s icy shell. NASA studies whether environments below the surface could support life; this is not evidence that life has been found. The surface map does not reveal the ocean directly.','多项证据支持木卫二冰壳下存在咸水海洋。NASA 研究其地下环境能否支持生命，这不等于已发现生命。表面地图不会直接显示地下海洋。','多項證據支持木衛二冰殼下存在鹹水海洋。NASA 研究其地下環境能否支持生命，這不等於已發現生命。表面地圖不會直接顯示地下海洋。','氷殻の下に塩水の海があることを強く支持する証拠があります。NASA は生命を支え得る環境を調べていますが、生命発見を意味しません。表面マップに地下の海は直接写っていません。','얼음 껍질 아래 염수 바다가 있다는 강한 증거가 있습니다. NASA는 생명을 지탱할 환경이 있는지 연구하지만 생명 발견을 뜻하지는 않습니다. 표면 지도에 지하 바다가 직접 보이지는 않습니다.'],
 '503':['jupiter/jupiter-moons/ganymede/','Ganymede is the largest moon in the solar system. It is the only moon known to generate its own magnetic field, with auroras around its poles. Its icy surface is mapped from spacecraft observations.','木卫三是太阳系最大的卫星，也是已知唯一产生自身磁场的卫星，极区存在极光。冰质表面的地图来自探测器观测。','木衛三是太陽系最大的衛星，也是已知唯一產生自身磁場的衛星，極區存在極光。冰質表面的地圖來自探測器觀測。','太陽系最大の衛星で、自身の磁場を持つことが知られる唯一の衛星です。極の周囲にオーロラがあり、氷の表面は探査機で観測されています。','태양계에서 가장 큰 위성이며 자체 자기장을 만드는 것으로 알려진 유일한 위성입니다. 극 주변에 오로라가 있으며 얼음 표면은 탐사선 관측으로 지도화되었습니다.'],
 '504':['jupiter/jupiter-moons/callisto/','Callisto is one of Jupiter’s four large Galilean moons. Its ancient, heavily cratered surface preserves a long impact history. Surface imagery and reference dimensions are available, but the globe here does not reconstruct crater depths.','木卫四是木星四颗大型伽利略卫星之一。古老而密布撞击坑的表面保存了漫长撞击历史。已有表面影像和参考尺寸，但本球体不重建坑深。','木衛四是木星四顆大型伽利略衛星之一。古老而密布撞擊坑的表面保存了漫長撞擊歷史。已有表面影像和參考尺寸，但本球體不重建坑深。','木星の 4 大ガリレオ衛星の一つです。古くクレーターの多い表面が長い衝突の歴史を残します。画像と基準寸法はありますが、この球体にクレーター深度はありません。','목성의 네 갈릴레이 대형 위성 중 하나입니다. 오래되고 분화구가 많은 표면이 긴 충돌 역사를 간직합니다. 영상과 기준 치수는 있지만 이 구체에 분화구 깊이는 없습니다.'],
 '602':['saturn/moons/enceladus/','An icy moon with a global subsurface ocean. Cassini observed plumes of water vapour and ice escaping near its south pole. The material feeds Saturn’s E ring and provides clues about ocean chemistry; habitability remains a scientific question.','土卫二是具有全球地下海洋的冰卫星。卡西尼观测到南极附近喷出水蒸气和冰粒，物质补充土星 E 环并提供海洋化学线索；是否适宜生命仍是科学问题。','土衛二是具有全球地下海洋的冰衛星。卡西尼觀測到南極附近噴出水蒸氣和冰粒，物質補充土星 E 環並提供海洋化學線索；是否適宜生命仍是科學問題。','全球的な地下海を持つ氷衛星です。カッシーニは南極付近からの水蒸気と氷の噴出を観測しました。物質は土星 E 環を補い、海の化学を知る手がかりになります。生命居住可能性は研究課題です。','전 지구 지하 바다를 가진 얼음 위성입니다. 카시니는 남극 부근에서 수증기와 얼음 분출을 관측했습니다. 물질은 토성 E 고리에 공급되고 바다 화학의 단서가 됩니다. 거주 가능성은 연구 과제입니다.'],
 '606':['saturn/moons/titan/','Saturn’s largest moon has a thick atmosphere and a surface liquid cycle. Lakes and seas contain hydrocarbons rather than terrestrial liquid water. Visible-light clouds and near-infrared surface maps show different layers of this world.','土卫六是土星最大的卫星，拥有浓密大气和地表液体循环。湖海含液态碳氢化合物，而不是地球式液态水。可见光云层和近红外地表图显示不同层次。','土衛六是土星最大的衛星，擁有濃密大氣和地表液體循環。湖海含液態碳氫化合物，而不是地球式液態水。可見光雲層和近紅外地表圖顯示不同層次。','土星最大の衛星で、厚い大気と地表の液体循環があります。湖や海は地球の水ではなく炭化水素です。可視光の雲と近赤外線の地表図は異なる層を見ています。','토성의 가장 큰 위성으로 짙은 대기와 지표 액체 순환이 있습니다. 호수와 바다는 지구의 액체 물이 아닌 탄화수소를 담고 있습니다. 가시광 구름과 근적외선 지표도는 다른 층을 보여줍니다.'],
 '801':['neptune/moons/triton/','Neptune’s largest moon follows a retrograde orbit, opposite the planet’s rotation. Its surface includes nitrogen frost, and Voyager 2 observed active geysers in 1989. Capture from the Kuiper Belt is a scientific interpretation of its unusual orbit.','海卫一是海王星最大的卫星，逆着行星自转方向公转。表面有氮霜，旅行者 2 号于 1989 年观测到活跃喷泉。从柯伊伯带俘获的说法是对其异常轨道的科学解释。','海衛一是海王星最大的衛星，逆著行星自轉方向公轉。表面有氮霜，旅行者 2 號於 1989 年觀測到活躍噴泉。從柯伊伯帶俘獲的說法是對其異常軌道的科學解釋。','海王星最大の衛星で、惑星の自転と逆向きに公転します。表面に窒素の霜があり、1989 年にボイジャー 2 号が噴出活動を観測しました。カイパーベルトからの捕獲は軌道を説明する仮説です。','해왕성의 가장 큰 위성으로 행성 자전과 반대로 공전합니다. 표면에 질소 서리가 있고 보이저 2호는 1989년 분출 활동을 관측했습니다. 카이퍼대에서 포획되었다는 것은 특이 궤도의 과학적 해석입니다.'],
 '901':['dwarf-planets/pluto/moons/charon/','Pluto’s largest moon is about half its parent’s diameter. Pluto and Charon always keep the same faces toward one another through mutual tidal locking. New Horizons images revealed a striking reddish north polar region.','卡戎是冥王星最大的卫星，直径约为母星的一半。两者相互潮汐锁定，始终以相同的一面相对。新视野号影像揭示了显著的红色北极区域。','卡戎是冥王星最大的衛星，直徑約為母星的一半。兩者相互潮汐鎖定，始終以相同的一面相對。新視野號影像揭示了顯著的紅色北極區域。','冥王星最大の衛星で直径は親天体の約半分です。互いに潮汐固定され、同じ面を向け合っています。ニュー・ホライズンズ画像は目立つ赤みのある北極域を示しました。','명왕성의 가장 큰 위성으로 지름은 중심 천체의 약 절반입니다. 서로 조석 고정되어 같은 면을 마주 봅니다. 뉴허라이즌스 영상에서 뚜렷하게 붉은 북극 지역이 확인되었습니다.'],
};
export const profiles=Object.fromEntries(Object.entries(rows).map(([key,[path,...text]])=>[key,{source:`https://science.nasa.gov/${path}`,checked:'2026-09-24',text}]));
